var exercisesDB = [
    {
        id: 1,
        name: 'Squat',
        primaryTarget: 'Quadriceps',
        secondaryTarget: ['Glutes', 'Hamstrings', 'Core'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 2,
        name: 'Goblet Squat',
        primaryTarget: 'Quadriceps',
        secondaryTarget: ['Glutes', 'Hamstrings'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 3,
        name: 'Leg Press',
        primaryTarget: 'Quadriceps',
        secondaryTarget: ['Quadriceps', 'Hamstrings'],
        equipment: 'Machine',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 4,
        name: 'Dynamic Lunges',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps', 'Hamstrings'],
        equipment: 'Dumbbells',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 5,
        name: 'Lunges',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps', 'Hamstrings'],
        equipment: 'Dumbbells',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 6,
        name: 'Deadlift',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings', 'Core'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 7,
        name: 'Romanian Deadlift',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings', 'Core'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    { id: 8, name: 'Leg Curl', primaryTarget: 'Hamstrings', equipment: 'Machine', weight: 'Light', isComplex: 0 },
    {
        id: 9,
        name: 'Bulgarian Split Squat',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps'],
        equipment: 'Dumbbells',
        weight: 'Moderate',
        isComplex: 1,
    },
    { id: 10, name: 'Calf Raise', primaryTarget: 'Calves', equipment: 'Machine', weight: 'Light', isComplex: 0 },
    {
        id: 11,
        name: 'Step-ups',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps', 'Hamstrings'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 12,
        name: 'Bench Step-ups',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps', 'Hamstrings'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 13,
        name: 'Sumo Squat',
        primaryTarget: 'Inner Thighs',
        secondaryTarget: ['Quadriceps', 'Glutes'],
        equipment: 'Dumbbell/Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 14,
        name: 'Cossack Squat',
        primaryTarget: 'Quadriceps',
        secondaryTarget: ['Glutes', 'Inner Thighs'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 15,
        name: 'Single-Leg Romanian Deadlift',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    { id: 16, name: 'Leg Extension', primaryTarget: 'Quadriceps', equipment: 'Machine', weight: 'Light', isComplex: 0 },
    {
        id: 17,
        name: 'Glute Bridge',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    { id: 18, name: 'Hamstring Curl', primaryTarget: 'Hamstrings', equipment: 'Machine', weight: 'Light', isComplex: 0 },
    { id: 19, name: 'Calf Raises (Seated/Standing)', primaryTarget: 'Calves', equipment: 'Machine', weight: 'Light', isComplex: 0 },
    {
        id: 20,
        name: 'Side Lunge',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps', 'Inner Thighs', ''],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 21,
        name: 'Kettlebell Swing',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings', 'Core', 'Soulders', 'Forearms'],
        equipment: 'Kettelebell',
        weight: 'Light',
        isComplex: 1,
    },
    { id: 22, name: 'Barbell Row', primaryTarget: 'Lats', secondaryTarget: ['Traps'], equipment: 'Barbell', weight: 'Moderate', isComplex: 1 },
    {
        id: 23,
        name: 'Lat Pulldown',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps', 'Biceps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 24,
        name: 'Pull-Ups',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps', 'Biceps'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    { id: 25, name: 'Dumbbell Row', primaryTarget: 'Lats', secondaryTarget: ['Traps'], equipment: 'Dumbbell', weight: 'Moderate', isComplex: 1 },
    { id: 26, name: 'T-Bar Row', primaryTarget: 'Lats', secondaryTarget: ['Traps'], equipment: 'Machine', weight: 'Moderate', isComplex: 1 },
    { id: 27, name: 'Cable Row', primaryTarget: 'Lats', secondaryTarget: ['Traps'], equipment: 'Machine', weight: 'Light', isComplex: 1 },
    {
        id: 28,
        name: 'Reverse Fly',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps', 'Shoulders'],
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 29,
        name: 'Hyperextensions',
        primaryTarget: 'Lats',
        secondaryTarget: ['Glutes', 'Hamstrings'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 30,
        name: 'Good Mornings',
        primaryTarget: 'Lats',
        secondaryTarget: ['Hamstrings'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    { id: 31, name: 'Seated Cable Row', primaryTarget: 'Lats', secondaryTarget: ['Traps'], equipment: 'Machine', weight: 'Light', isComplex: 1 },
    { id: 32, name: 'Inverted Row', primaryTarget: 'Lats', secondaryTarget: ['Traps'], equipment: 'Bodyweight', weight: 'Light', isComplex: 1 },
    { id: 33, name: 'Pullover', primaryTarget: 'Lats', equipment: 'Dumbbell', weight: 'Light', isComplex: 0 },
    {
        id: 34,
        name: 'Renegade Row',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps', 'Core'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 35,
        name: 'Straight Arm Pulldown',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 36,
        name: 'Close-Grip Lat Pulldown',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 37,
        name: 'Wide-Grip Pull-Ups',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 38,
        name: 'Bent-Over Row',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Barbell/Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 39,
        name: 'Reverse Grip Bent-Over Row',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Barbell/Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 40,
        name: 'Single-Arm Dumbbell Row',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 41,
        name: 'Cable Lat Pulldown',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 42,
        name: 'Eccentric Pull-Ups',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 43,
        name: 'Eccentric Chin-Ups',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 44,
        name: 'Eccentric Deadlifts',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 45,
        name: 'Eccentric Bent-Over Row',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Barbell/Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 46,
        name: 'Eccentric Lat Pulldown',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 47,
        name: 'Rack Pulls',
        primaryTarget: 'Back',
        secondaryTarget: ['Glutes', 'Hamstrings'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 0,
    },
    {
        id: 48,
        name: 'Bench Press',
        primaryTarget: 'Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 49,
        name: 'Dumbbell Bench Press',
        primaryTarget: 'Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 50,
        name: 'Incline Bench Press',
        primaryTarget: 'Upper Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 51,
        name: 'Decline Bench Press',
        primaryTarget: 'Lower Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 52,
        name: 'Push-Ups',
        primaryTarget: 'Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 53,
        name: 'Dips',
        primaryTarget: 'Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Bodyweight',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 54,
        name: 'Cable Chest Press',
        primaryTarget: 'Chest',
        secondaryTarget: ['Triceps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    { id: 55, name: 'Chest Fly', primaryTarget: 'Chest', secondaryTarget: ['Shoulders'], equipment: 'Dumbbell', weight: 'Light', isComplex: 0 },
    {
        id: 56,
        name: 'Incline Dumbbell Press',
        primaryTarget: 'Upper Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 57,
        name: 'Decline Dumbbell Press',
        primaryTarget: 'Lower Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 58,
        name: 'Push-Up Variations',
        primaryTarget: 'Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 59,
        name: 'Machine Chest Press',
        primaryTarget: 'Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    { id: 60, name: 'Pec Deck Fly', primaryTarget: 'Chest', secondaryTarget: ['Shoulders'], equipment: 'Machine', weight: 'Light', isComplex: 0 },
    {
        id: 61,
        name: 'Barbell Pullover',
        primaryTarget: 'Chest',
        secondaryTarget: ['Lats', 'Shoulders'],
        equipment: 'Barbell',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 62,
        name: 'Dumbbell Pullover',
        primaryTarget: 'Lats',
        secondaryTarget: ['Shoulders'],
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 63,
        name: 'Cable Crossover',
        primaryTarget: 'Chest',
        secondaryTarget: ['Shoulders'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 64,
        name: 'Incline Cable Fly',
        primaryTarget: 'Upper Chest',
        secondaryTarget: ['Shoulders'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 65,
        name: 'Decline Cable Fly',
        primaryTarget: 'Lower Chest',
        secondaryTarget: ['Shoulders'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 66,
        name: 'Squeeze Press',
        primaryTarget: 'Chest',
        secondaryTarget: ['Triceps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    { id: 67, name: 'Floor Press', primaryTarget: 'Chest', secondaryTarget: ['Triceps'], equipment: 'Barbell', weight: 'Moderate', isComplex: 1 },
    {
        id: 68,
        name: 'Medicine Ball Chest Pass',
        primaryTarget: 'Chest',
        secondaryTarget: ['Shoulders'],
        equipment: 'Medicine Ball',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 69,
        name: 'Plyometric Push-Ups',
        primaryTarget: 'Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 70,
        name: 'Smith Machine Bench Press',
        primaryTarget: 'Chest',
        secondaryTarget: ['Triceps', 'Shoulders'],
        equipment: 'Smith Machine',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 71,
        name: 'Military Press',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Triceps'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 72,
        name: 'Dumbbell Shoulder Press',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Triceps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 73,
        name: 'Arnold Press',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Triceps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 74,
        name: 'Barbell Overhead Press',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Triceps'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 75,
        name: 'Seated Dumbbell Press',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Triceps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    { id: 76, name: 'Push Press', primaryTarget: 'Shoulders', secondaryTarget: ['Triceps'], equipment: 'Barbell', weight: 'Heavy', isComplex: 1 },
    { id: 77, name: 'Lateral Raises', primaryTarget: 'Shoulders', equipment: 'Dumbbell', weight: 'Light', isComplex: 0 },
    { id: 78, name: 'Front Raises', primaryTarget: 'Shoulders', equipment: 'Dumbbell', weight: 'Light', isComplex: 0 },
    { id: 79, name: 'Bent-Over Lateral Raises', primaryTarget: 'Shoulders', equipment: 'Dumbbell', weight: 'Light', isComplex: 0 },
    { id: 80, name: 'Upright Row', primaryTarget: 'Shoulders', equipment: 'Barbell', weight: 'Moderate', isComplex: 1 },
    { id: 81, name: 'Shrugs', primaryTarget: 'Shoulders', secondaryTarget: ['Traps'], equipment: 'Barbell', weight: 'Moderate', isComplex: 0 },
    {
        id: 82,
        name: 'Cable Shoulder Press',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Triceps'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 83,
        name: 'Standing Military Press',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Triceps'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 84,
        name: 'Machine Shoulder Press',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Triceps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 85,
        name: 'Reverse Flyes',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Traps'],
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 86,
        name: 'Face Pulls',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Traps'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 1,
    },
    { id: 87, name: 'Rear Delt Raises', primaryTarget: 'Shoulders', equipment: 'Dumbbell', weight: 'Light', isComplex: 0 },
    {
        id: 88,
        name: 'Dumbbell Shrug',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Traps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 0,
    },
    {
        id: 89,
        name: 'Kettlebell Press',
        primaryTarget: 'Shoulders',
        secondaryTarget: ['Triceps'],
        equipment: 'Kettlebell',
        weight: 'Moderate',
        isComplex: 1,
    },
    { id: 90, name: 'Barbell Curl', primaryTarget: 'Biceps', equipment: 'Barbell', weight: 'Moderate', isComplex: 0 },
    { id: 91, name: 'Dumbbell Curl', primaryTarget: 'Biceps', equipment: 'Dumbbell', weight: 'Moderate', isComplex: 0 },
    { id: 92, name: 'Hammer Curl', primaryTarget: 'Biceps', equipment: 'Dumbbell', weight: 'Moderate', isComplex: 0 },
    { id: 93, name: 'Preacher Curl', primaryTarget: 'Biceps', equipment: 'Barbell', weight: 'Moderate', isComplex: 0 },
    { id: 94, name: 'Cable Curl', primaryTarget: 'Biceps', equipment: 'Cable', weight: 'Light', isComplex: 0 },
    { id: 95, name: 'Concentration Curl', primaryTarget: 'Biceps', equipment: 'Dumbbell', weight: 'Light', isComplex: 0 },
    { id: 96, name: 'EZ Bar Curl', primaryTarget: 'Biceps', equipment: 'EZ Bar', weight: 'Moderate', isComplex: 0 },
    { id: 97, name: 'Incline Dumbbell Curl', primaryTarget: 'Biceps', equipment: 'Dumbbell', weight: 'Light', isComplex: 0 },
    { id: 98, name: 'Spider Curl', primaryTarget: 'Biceps', equipment: 'Barbell', weight: 'Light', isComplex: 0 },
    {
        id: 99,
        name: 'Close-Grip Bench Press',
        primaryTarget: 'Triceps',
        secondaryTarget: ['Shoulders'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    { id: 100, name: 'Tricep Dips', primaryTarget: 'Triceps', equipment: 'Bodyweight', weight: 'Moderate', isComplex: 1 },
    { id: 101, name: 'Skull Crushers', primaryTarget: 'Triceps', equipment: 'Barbell', weight: 'Moderate', isComplex: 0 },
    { id: 102, name: 'Tricep Pushdown', primaryTarget: 'Triceps', equipment: 'Cable', weight: 'Light', isComplex: 1 },
    { id: 103, name: 'Overhead Tricep Extension', primaryTarget: 'Triceps', equipment: 'Dumbbell', weight: 'Light', isComplex: 0 },
    { id: 104, name: 'Cable Tricep Extension', primaryTarget: 'Triceps', equipment: 'Cable', weight: 'Light', isComplex: 0 },
    { id: 105, name: 'Tricep Kickbacks', primaryTarget: 'Triceps', equipment: 'Dumbbell', weight: 'Light', isComplex: 0 },
    { id: 106, name: 'Diamond Push-Ups', primaryTarget: 'Triceps', equipment: 'Bodyweight', weight: 'Light', isComplex: 1 },
    { id: 107, name: 'Reverse Grip Curl', primaryTarget: 'Biceps', equipment: 'Barbell', weight: 'Moderate', isComplex: 0 },
    { id: 108, name: 'Hammer Curl Machine', primaryTarget: 'Biceps', equipment: 'Machine', weight: 'Light', isComplex: 0 },
    { id: 109, name: 'Standing Tricep Extension', primaryTarget: 'Triceps', equipment: 'Dumbbell', weight: 'Moderate', isComplex: 0 },
    { id: 110, name: 'Rope Tricep Pushdown', primaryTarget: 'Triceps', equipment: 'Cable', weight: 'Light', isComplex: 0 },
    { id: 111, name: 'Hammer Curl Rope', primaryTarget: 'Biceps', equipment: 'Cable', weight: 'Light', isComplex: 0 },
];
