var exercisesDB = [
    {
        id: 1,
        name: 'Squat',
        area: 'Legs',
        primaryTarget: 'Quadriceps',
        secondaryTarget: ['Glutes', 'Hamstrings', 'Core'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 2,
        name: 'Goblet Squat',
        area: 'Legs',
        primaryTarget: 'Quadriceps',
        secondaryTarget: ['Glutes', 'Hamstrings'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 3,
        name: 'Leg Press',
        area: 'Legs',
        primaryTarget: 'Quadriceps',
        secondaryTarget: ['Quadriceps', 'Hamstrings'],
        equipment: 'Machine',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 4,
        name: 'Dynamic Lunges',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps', 'Hamstrings'],
        equipment: 'Dumbbells',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 5,
        name: 'Lunges',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps', 'Hamstrings'],
        equipment: 'Dumbbells',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 6,
        name: 'Deadlift',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings', 'Core'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 7,
        name: 'Romanian Deadlift',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings', 'Core'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 8,
        name: 'Leg Curl',
        area: 'Legs',
        primaryTarget: 'Hamstrings',
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 9,
        name: 'Bulgarian Split Squat',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps'],
        equipment: 'Dumbbells',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 10,
        name: 'Calf Raise',
        area: 'Legs',
        primaryTarget: 'Calves',
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 11,
        name: 'Step-ups',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps', 'Hamstrings'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 12,
        name: 'Bench Step-ups',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps', 'Hamstrings'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 13,
        name: 'Sumo Squat',
        area: 'Legs',
        primaryTarget: 'Inner Thighs',
        secondaryTarget: ['Quadriceps', 'Glutes'],
        equipment: 'Dumbbell/Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 14,
        name: 'Cossack Squat',
        area: 'Legs',
        primaryTarget: 'Quadriceps',
        secondaryTarget: ['Glutes', 'Inner Thighs'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 15,
        name: 'Single-Leg Romanian Deadlift',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 16,
        name: 'Leg Extension',
        area: 'Legs',
        primaryTarget: 'Quadriceps',
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 17,
        name: 'Glute Bridge',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 18,
        name: 'Hamstring Curl',
        area: 'Legs',
        primaryTarget: 'Hamstrings',
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 19,
        name: 'Calf Raises (Seated/Standing)',
        area: 'Legs',
        primaryTarget: 'Calves',
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 20,
        name: 'Side Lunge',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Quadriceps', 'Inner Thighs', ''],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 21,
        name: 'Kettlebell Swing',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings', 'Core', 'Deltoids', 'Forearms'],
        equipment: 'Kettelebell',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 22,
        name: 'Barbell Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 23,
        name: 'Lat Pulldown',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps', 'Biceps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 24,
        name: 'Pull-Ups',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps', 'Biceps'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 25,
        name: 'Dumbbell Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 26,
        name: 'T-Bar Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Machine',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 27,
        name: 'Cable Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 28,
        name: 'Reverse Fly',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps', 'Deltoids'],
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 29,
        name: 'Hyperextensions',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Glutes', 'Hamstrings'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 30,
        name: 'Good Mornings',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Hamstrings'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 31,
        name: 'Seated Cable Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 32,
        name: 'Inverted Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 33,
        name: 'Pullover',
        area: 'Back',
        primaryTarget: 'Lats',
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 34,
        name: 'Renegade Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps', 'Core'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 35,
        name: 'Straight Arm Pulldown',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 36,
        name: 'Close-Grip Lat Pulldown',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 37,
        name: 'Wide-Grip Pull-Ups',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 38,
        name: 'Bent-Over Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Barbell/Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 39,
        name: 'Reverse Grip Bent-Over Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Barbell/Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 40,
        name: 'Single-Arm Dumbbell Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 41,
        name: 'Cable Lat Pulldown',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 42,
        name: 'Eccentric Pull-Ups',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 43,
        name: 'Eccentric Chin-Ups',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 44,
        name: 'Eccentric Deadlifts',
        area: 'Legs',
        primaryTarget: 'Glutes',
        secondaryTarget: ['Hamstrings'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 45,
        name: 'Eccentric Bent-Over Row',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Traps'],
        equipment: 'Barbell/Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 46,
        name: 'Eccentric Lat Pulldown',
        area: 'Back',
        primaryTarget: 'Lats',
        secondaryTarget: ['Biceps', 'Traps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 47,
        name: 'Rack Pulls',
        area: 'Back',
        primaryTarget: 'Back',
        secondaryTarget: ['Glutes', 'Hamstrings'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 0,
    },
    {
        id: 48,
        name: 'Bench Press',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 49,
        name: 'Dumbbell Bench Press',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 50,
        name: 'Incline Bench Press',
        area: 'Chest',
        primaryTarget: 'Upper Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 51,
        name: 'Decline Bench Press',
        area: 'Chest',
        primaryTarget: 'Lower Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 52,
        name: 'Push-Ups',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 53,
        name: 'Dips',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Bodyweight',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 54,
        name: 'Cable Chest Press',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 55,
        name: 'Chest Fly',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Deltoids'],
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 56,
        name: 'Incline Dumbbell Press',
        area: 'Chest',
        primaryTarget: 'Upper Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 57,
        name: 'Decline Dumbbell Press',
        area: 'Chest',
        primaryTarget: 'Lower Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 58,
        name: 'Push-Up Variations',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 59,
        name: 'Machine Chest Press',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 60,
        name: 'Pec Deck Fly',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Deltoids'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 61,
        name: 'Barbell Pullover',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Lats', 'Deltoids'],
        equipment: 'Barbell',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 62,
        name: 'Dumbbell Pullover',
        area: 'Chest',
        primaryTarget: 'Lats',
        secondaryTarget: ['Deltoids'],
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 63,
        name: 'Cable Crossover',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Deltoids'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 64,
        name: 'Incline Cable Fly',
        area: 'Chest',
        primaryTarget: 'Upper Pectoralis',
        secondaryTarget: ['Deltoids'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 65,
        name: 'Decline Cable Fly',
        area: 'Chest',
        primaryTarget: 'Lower Pectoralis',
        secondaryTarget: ['Deltoids'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 66,
        name: 'Squeeze Press',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 67,
        name: 'Floor Press',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 68,
        name: 'Medicine Ball Chest Pass',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Deltoids'],
        equipment: 'Medicine Ball',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 69,
        name: 'Plyometric Push-Ups',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 70,
        name: 'Smith Machine Bench Press',
        area: 'Chest',
        primaryTarget: 'Pectoralis',
        secondaryTarget: ['Triceps', 'Deltoids'],
        equipment: 'Smith Machine',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 71,
        name: 'Military Press',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Triceps'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 72,
        name: 'Dumbbell Shoulder Press',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Triceps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 73,
        name: 'Arnold Press',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Triceps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 74,
        name: 'Barbell Overhead Press',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Triceps'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 75,
        name: 'Seated Dumbbell Press',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Triceps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 76,
        name: 'Push Press',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Triceps'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 77,
        name: 'Lateral Raises',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 78,
        name: 'Front Raises',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 79,
        name: 'Bent-Over Lateral Raises',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 80,
        name: 'Upright Row',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
        secondaryTarget: [],
    },
    {
        id: 81,
        name: 'Shrugs',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Traps'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 0,
    },
    {
        id: 82,
        name: 'Cable Shoulder Press',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Triceps'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 83,
        name: 'Standing Military Press',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Triceps'],
        equipment: 'Barbell',
        weight: 'Heavy',
        isComplex: 1,
    },
    {
        id: 84,
        name: 'Machine Shoulder Press',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Triceps'],
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 85,
        name: 'Reverse Flyes',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Traps'],
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
    },
    {
        id: 86,
        name: 'Face Pulls',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Traps'],
        equipment: 'Cable Machine',
        weight: 'Light',
        isComplex: 1,
    },
    {
        id: 87,
        name: 'Rear Delt Raises',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 88,
        name: 'Dumbbell Shrug',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Traps'],
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 0,
    },
    {
        id: 89,
        name: 'Kettlebell Press',
        area: 'Shoulders',
        primaryTarget: 'Deltoids',
        secondaryTarget: ['Triceps'],
        equipment: 'Kettlebell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 90,
        name: 'Barbell Curl',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 91,
        name: 'Dumbbell Curl',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 92,
        name: 'Hammer Curl',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 93,
        name: 'Preacher Curl',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 94,
        name: 'Cable Curl',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Cable',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 95,
        name: 'Concentration Curl',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 96,
        name: 'EZ Bar Curl',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'EZ Bar',
        weight: 'Moderate',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 97,
        name: 'Incline Dumbbell Curl',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 98,
        name: 'Spider Curl',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Barbell',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 99,
        name: 'Close-Grip Bench Press',
        area: 'Arms',
        primaryTarget: 'Triceps',
        secondaryTarget: ['Deltoids'],
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 1,
    },
    {
        id: 100,
        name: 'Tricep Dips',
        area: 'Arms',
        primaryTarget: 'Triceps',
        equipment: 'Bodyweight',
        weight: 'Moderate',
        isComplex: 1,
        secondaryTarget: [],
    },
    {
        id: 101,
        name: 'Skull Crushers',
        area: 'Arms',
        primaryTarget: 'Triceps',
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 102,
        name: 'Tricep Pushdown',
        area: 'Arms',
        primaryTarget: 'Triceps',
        equipment: 'Cable',
        weight: 'Light',
        isComplex: 1,
        secondaryTarget: [],
    },
    {
        id: 103,
        name: 'Overhead Tricep Extension',
        area: 'Arms',
        primaryTarget: 'Triceps',
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 104,
        name: 'Cable Tricep Extension',
        area: 'Arms',
        primaryTarget: 'Triceps',
        equipment: 'Cable',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 105,
        name: 'Tricep Kickbacks',
        area: 'Arms',
        primaryTarget: 'Triceps',
        equipment: 'Dumbbell',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 106,
        name: 'Diamond Push-Ups',
        area: 'Arms',
        primaryTarget: 'Triceps',
        equipment: 'Bodyweight',
        weight: 'Light',
        isComplex: 1,
        secondaryTarget: [],
    },
    {
        id: 107,
        name: 'Reverse Grip Curl',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Barbell',
        weight: 'Moderate',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 108,
        name: 'Hammer Curl Machine',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Machine',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 109,
        name: 'Standing Tricep Extension',
        area: 'Arms',
        primaryTarget: 'Triceps',
        equipment: 'Dumbbell',
        weight: 'Moderate',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 110,
        name: 'Rope Tricep Pushdown',
        area: 'Arms',
        primaryTarget: 'Triceps',
        equipment: 'Cable',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
    {
        id: 111,
        name: 'Hammer Curl Rope',
        area: 'Arms',
        primaryTarget: 'Biceps',
        equipment: 'Cable',
        weight: 'Light',
        isComplex: 0,
        secondaryTarget: [],
    },
];
